# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.cache/wt} [current_project]
set_property parent.project_path {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/ALU28.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/OutputBCD.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/Register28.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/StateMachine.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/SwitchFormat.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/TriBuffer28.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/Sources/bcdSelect.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/imports/Sources/bcdToSeg7.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/bit12binToBCD.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/checkNeg.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/Sources/clkDivider.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/Sources/clkDivider7Seg.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/completeBCD.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/doubleDabble.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/Sources/shiftRegister3Segs.vhd}
  {C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/sources_1/new/CalculatorProject.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/constrs_1/imports/Constraints/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/ADAM/Desktop/ENEL373 Digital Electronics and Devices/CalculatorProject/CalculatorProject/CalculatorProject.srcs/constrs_1/imports/Constraints/Nexys4DDR_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CalculatorProject -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CalculatorProject.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CalculatorProject_utilization_synth.rpt -pb CalculatorProject_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
